apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: my-vcluster
    server: 'https://kubernetes.default.svc'
  source:
    path: vcluster
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.25.0-beta.2
    chart: vcluster
    helm:
      releaseName: argocd
      values: |
        controlPlane:
          # Deploy etcd instead of using the embedded SQLite
          backingStore:
            etcd:
              deploy:
                enabled: true
                statefulSet:
                  highAvailability:
                    replicas: 3
          # Deploy vCluster with 3 replicas
          statefulSet:
            highAvailability:
              replicas: 3
  sources: []
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  project: default
