apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdv2
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: my-other-vcluster
    server: 'https://kubernetes.default.svc'
  source:
    path: vcluster
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.25.0-beta.2
    chart: vcluster
    helm:
      releaseName: othervc
      values: |
        sync:
          fromHost:
            configMaps:
              enabled: true
              mappings:
                byName:
                  # syncs specific ConfigMaps from vCluster's host namespace
                  # to my-virtual-namespace in vCluster.
                  "": "my-virtual-namespace/my-cm-1"
  sources: []
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  project: default
